name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Show Node-Environment
        run: node -v && npm -v && npx nx report

      - name: Build Angular app
        run: npx nx build portfolio --configuration=production --verbose

      - name: Upload build as artifact (for PR inspection)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: portfolio-docs
          path: docs

      - name: Prepare 404-fallback & disable Jekyll
        if: github.event_name == 'push'
        run: |
          cp docs/index.html docs/404.html
          touch docs/.nojekyll

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
          clean: true
          token: ${{ secrets.GH_PAGES_TOKEN }}
